name: SunEssentials
version: 1.3
author: VincentCoding
main: fr.vcoding.sunessentials.Main

commands:
  gm:
    description: Change your gamemode
    permission: gm.use
  suicide:
    description: Kill yourself
    permission: kill.use
  sk:
    description: Kill a selected entity
    permission: kill.use
  bc:
    description: Alias of alert
    permission: bc.use
  alert:
    description: Send a message to all players
    permission: bc.use
  reffect:
    description: Remove all potions effects from a player
    permission: reset.use
  vanish:
    description: Used to make a player invisible to other players
    permission: vanish.use
  unvanish:
    description: Used to make a player visible to other players
    permission: vanish.use
  day:
    description: Used to set the day
    permission: time.use
  night:
    description: Used to set the night
    permission: time.use
  wclear:
    description: Used to remove rain
    permission: time.use
  storm:
    description: Used to put the storm
    permission: time.use
  wrain:
    description: Used to put the rain
    permission: time.use
  wc:
    description: Alias of wclear
    permission: time.use
  wr:
    description: Alias of wrain
    permission: time.use
  ws:
    description: Alias of storm
    permission: time.use
  fly:
    description: Allows you to activate or deactivate the fly
    permission: fly.use
  explode:
    description: Blows up a player
    permission: kill.use
  top:
    description: Allows to teleport to layer 255
    permission: top.use